export enum CartTypes {
  CART_SET = 'CART/SET',
  CART_ADD = 'CART/ADD',
  CART_REMOVE = 'CART/REMOVE',
  CART_QUANTITY_INCREMENT = 'CART/QUANTITY_INCREMENT',
  CART_QUANTITY_DECREMENT = 'CART/QUANTITY_DECREMENT',
}
